  name: Commit Stage
  on: push

  jobs:
    build:
      name: Build and Test
      runs-on: self-hosted
      permissions:
        contents: read
        security-events: read
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
            cache: maven
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.33.0
          id: scan
          with:
            image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
            format: 'sarif'
            output: 'trivy-report.sarif'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

        - name: Upload vulnerability report
          uses: github/codeql-action/upload-sarif@v2
          if: success() || failure()
          with:
            sarif_file: trivy-report.sarif
        - name: Build, unit test and integration test
          run: |
            chmod +x mvnw
            ./mvnw clean verify
