  name: Commit Stage
  on: push

  jobs:
    build:
      name: Build and Test
      runs-on: self-hosted
      permissions:
        contents: read
        security-events: read
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
            cache: maven
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@v0.15.0
          id: scan
          with:
            scan-type: fs
            ignore-unfixed: true
            format: sarif
            output: trivy-results.sarif
            exit-code: 0

        - name: Upload vulnerability report
          uses: github/codeql-action/upload-sarif@v2
          if: success() || failure()
          with:
            sarif_file: ${{ steps.scan.outputs.sarif }}
        - name: Build, unit test and integration test
          run: |
            chmod +x mvnw
            ./mvnw clean verify
